### PR TITLE
le fixt

### PR DESCRIPTION
**Pull request by bitemyapp**
'tis fixt yo. :)

### CODE REVIEW

**Comment by rodnaph** [comment]
Thanks, what's lib-noir for?

**Comment by bitemyapp** [comment]
@rodnaph Noir is dead yo. Bunch of libraries got parted out, some of the ones you're implicitly/explicitly using live in lib-noir.

**Comment by rodnaph** [comment]
Yes I know its deprecated, but didn't realise any of these dependencies were part of noir though - for my knowledge can you tell me which ones?

**Comment by bitemyapp** [comment]
I'm sick and semi-delirious. So not at the moment, no.

Could remove it and see what breaks. Science is awesome.

**Comment by rodnaph** [comment]
afaik this project does not use any of the lib-noir components, please re-open and correct me if i'm wrong.

**Pull request closed without merging**
